# Generated by Django 6.0.4 on 2026-05-01 01:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='stripe_coupon_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='stripe_tax_rate_id',
        ),
        migrations.AddField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], default='percentage', max_length=20, verbose_name='Type of discount'),
        ),
        migrations.AddField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percentage'),
        ),
    ]
